name: build

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python info
      shell: bash -e {0}
      run: |
        which python
        python --version
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install --upgrade spacy
        pip3 install pytextrank
        python -m spacy download en_core_web_md
        python -m nltk.downloader stopwords
    - name: Run unit tests
      run: |
        pip install pytest pytest-cov
        run: python -m pytest --cov --cov-report term --cov-report xml --cov-report html --junitxml=xunit-result.xml ./tests

# uncomment when project has been added to coveralls and the COVERALLS_REPO_TOKEN has been added to secrets 
#    - name: Coveralls GitHub Action
#      uses: coverallsapp/github-action@v2
#      with:
#        github-token: $ {{ secrets.GITHUB_TOKEN }} # (remove space between $( )
#        path-to-lcov: coverage.xml