name: FAReviews code style check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "feature/performance_improvement2" ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ "feature/performance_improvement2" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install additional dependencies
        run: |
          pip install flake8
      - name: Check code style
        run: |
          flake8
